# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe88db263e60909524cba2b2c8989025c772520589adcfa53c773bfc52f230092832314db308b889ca3cf3d7233809849c557964dee972467369e41be09fec1

test:
  secret_key_base: 7d9074b76f8eb35a9e3b5b944faaadbfa1cebd45fbdd377fe82f5444205d5cef11390832dcc7bb1cdc17df6284091340b63376ff0f29e68b90582e77ca2bfe73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
